# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14JPLUNUrkhDxKbY9M6kVuWN9gJsYV4Aa
"""

from win10toast import TioastNotifier
import time

while 1:
    current_time = time.strftime("%H:%M:%S")
    if current_time = " 00.30.00":
      print('current time')
    break
    else: pass

hr = TioastNotifier()
hr.show_toasr("Alaram , This is the massage!")